cabal-version:       3.0
name:                Pref
version:             0.7.0.0
license:             BSD-3-Clause
license-file:        LICENSE
author:              Turab Jafri
build-type:          Simple
extra-source-files:  CHANGELOG.md,
                     README.md

common deps
  build-depends:       base >=4.12 && <5,
                       mtl >= 2.2.2,
                       text >= 1.2.3
common language
  default-language:    Haskell2010
  ghc-options:         -Wall
                       -Wcompat
                       -Wincomplete-record-updates
                       -Wincomplete-uni-patterns
                       -Wredundant-constraints

library
  import:              deps, language
  hs-source-dirs:      src
  exposed-modules:     Pref,
                       Syntax.Exp,
                       TH, 
                       Transform.Uniquify,
                       Transform.CPS
  other-modules:       Example.THExample,
                       Errors,
                       Lexer,
                       Parser
  build-depends:       containers,
                       dlist == 1.*,
                       parsec >=3.1 && <4,
                       prettyprinter >= 1.3.0,
                       template-haskell >= 2.14,

executable cps
  import:              deps, language
  main-is:             src/CpsApp.hs
  build-depends:       Pref,
                       optparse-applicative >= 0.15.0 && <1

executable pref
  import:              deps, language
  main-is:             src/Main.hs
  build-depends:       Pref >=0.3.0.0,
                       optparse-applicative >= 0.15.0 && <1

test-suite pref-tests
  import:              deps, language
  type:                exitcode-stdio-1.0
  hs-source-dirs:      tests
  main-is:             Main.hs
  other-modules:       ParserTests,
                       InterpTests,
                       Transform.CpserTests,
                       Transform.UniquifyTests
  build-depends:       Pref,
                       containers,
                       filepath >=1.4.2 && <2,
                       tasty >= 1.2.3 && <2,
                       tasty-golden >= 2.3.3 && <3,
                       tasty-hunit >= 0.10.0 && <1
